name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        id: rustup
        with:
          profile: minimal
          toolchain: stable
          override: true
            
      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.10
      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.9
      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8
        
      - run: pip install tox
          
          # TODO: this can be moved into a separate file
      - name: Run Core library tests
        # we don't have a GPU in CI so disable the gpu feature
        run: |
          cd facet-core
          cargo test --no-default-features --features=rayon
          
      - name: Run Python tests
        run: tox
