name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        id: rustup
        with:
          profile: minimal
          toolchain: stable
          override: true
            
      - name: Setup Python
        run: sudo apt install -y python3-dev python3-pip
  
      - run: |
          which python
          which pip
          pip --version
          python --version
        
      - run: pip3 install tox pytest setuptools setuptools-rust
          
          # TODO: this can be moved into a separate file
      - name: Run Core library tests
        run: |
          cd facet-core
          cargo test
        
      - name: Install
        run: |
          cd pyfacet
          pip3 install -e.
          
      - name: Run Python tests
        run: pytest tests
