name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        id: rustup
        with:
          profile: minimal
          toolchain: stable
          override: true
            
      - name: Setup Python
        run: sudo apt install -y python3-dev python3-pip
          
      - run: |
          which python
          which pip
          
      - run: pip install pytest tox setuptools setuptools-rust
          
      - name: Run Rust tests
        run: cargo test
        
      - name: Install
        run: |
          make install
          
      - name: Run Python tests
        run: |
          cd pyfacet
          tox
