name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        id: rustup
        with:
          profile: minimal
          toolchain: stable
          override: true
            
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - run: which python
      - run: pip install -r requirements.txt
          
      - name: Run Rust tests
        run: cargo test
        
      - name: Install pyfacet
        run: |
          cd pyfacet
          maturin develop --cargo-extra-args="--no-default-features"
          
      - name: Run Python tests
        run: |
          pytest tests/
